import ground from './ground.png'
import pec1 from './pec1.png'
import pec2 from './pec2.png'
import pec3 from './pec3.png'
import pec4 from './pec4.png'
import arrow from './arrow.png'
import button  from './button.png'
import byc  from './byc.png'
import star from './star.png'
import aple from './aple.png'
import car from './car.png'
import boxer1 from './boxer1.png'
import boxer2 from './boxer2.png'
import boxer3 from './boxer3.png'
import boxer4 from './boxer4.png'
import shot from './shot.png'
import caba from './caba.png'
import visa from './visa.png'


export{ground,pec1,pec2,pec3,pec4,arrow,button,byc,star,aple,car,boxer1,boxer2,boxer3,boxer4,shot,caba,visa}